#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_WebDienThoai.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DA_WebBanDienThoai")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchitietdathang(chitietdathang instance);
    partial void Updatechitietdathang(chitietdathang instance);
    partial void Deletechitietdathang(chitietdathang instance);
    partial void Insertdathang(dathang instance);
    partial void Updatedathang(dathang instance);
    partial void Deletedathang(dathang instance);
    partial void Insertnhasanxuat(nhasanxuat instance);
    partial void Updatenhasanxuat(nhasanxuat instance);
    partial void Deletenhasanxuat(nhasanxuat instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    partial void Inserttintuc(tintuc instance);
    partial void Updatetintuc(tintuc instance);
    partial void Deletetintuc(tintuc instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DA_WebBanDienThoaiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chitietdathang> chitietdathangs
		{
			get
			{
				return this.GetTable<chitietdathang>();
			}
		}
		
		public System.Data.Linq.Table<dathang> dathangs
		{
			get
			{
				return this.GetTable<dathang>();
			}
		}
		
		public System.Data.Linq.Table<nhasanxuat> nhasanxuats
		{
			get
			{
				return this.GetTable<nhasanxuat>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<tintuc> tintucs
		{
			get
			{
				return this.GetTable<tintuc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietdathang")]
	public partial class chitietdathang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ctdh_madh;
		
		private System.Nullable<int> _ctdh_makh;
		
		private System.Nullable<System.DateTime> _ctdh_ngaylap;
		
		private System.Nullable<int> _ctdh_tongtien;
		
		private EntitySet<dathang> _dathangs;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onctdh_madhChanging(int value);
    partial void Onctdh_madhChanged();
    partial void Onctdh_makhChanging(System.Nullable<int> value);
    partial void Onctdh_makhChanged();
    partial void Onctdh_ngaylapChanging(System.Nullable<System.DateTime> value);
    partial void Onctdh_ngaylapChanged();
    partial void Onctdh_tongtienChanging(System.Nullable<int> value);
    partial void Onctdh_tongtienChanged();
    #endregion
		
		public chitietdathang()
		{
			this._dathangs = new EntitySet<dathang>(new Action<dathang>(this.attach_dathangs), new Action<dathang>(this.detach_dathangs));
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctdh_madh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ctdh_madh
		{
			get
			{
				return this._ctdh_madh;
			}
			set
			{
				if ((this._ctdh_madh != value))
				{
					this.Onctdh_madhChanging(value);
					this.SendPropertyChanging();
					this._ctdh_madh = value;
					this.SendPropertyChanged("ctdh_madh");
					this.Onctdh_madhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctdh_makh", DbType="Int")]
		public System.Nullable<int> ctdh_makh
		{
			get
			{
				return this._ctdh_makh;
			}
			set
			{
				if ((this._ctdh_makh != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onctdh_makhChanging(value);
					this.SendPropertyChanging();
					this._ctdh_makh = value;
					this.SendPropertyChanged("ctdh_makh");
					this.Onctdh_makhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctdh_ngaylap", DbType="Date")]
		public System.Nullable<System.DateTime> ctdh_ngaylap
		{
			get
			{
				return this._ctdh_ngaylap;
			}
			set
			{
				if ((this._ctdh_ngaylap != value))
				{
					this.Onctdh_ngaylapChanging(value);
					this.SendPropertyChanging();
					this._ctdh_ngaylap = value;
					this.SendPropertyChanged("ctdh_ngaylap");
					this.Onctdh_ngaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctdh_tongtien", DbType="Int")]
		public System.Nullable<int> ctdh_tongtien
		{
			get
			{
				return this._ctdh_tongtien;
			}
			set
			{
				if ((this._ctdh_tongtien != value))
				{
					this.Onctdh_tongtienChanging(value);
					this.SendPropertyChanging();
					this._ctdh_tongtien = value;
					this.SendPropertyChanged("ctdh_tongtien");
					this.Onctdh_tongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chitietdathang_dathang", Storage="_dathangs", ThisKey="ctdh_madh", OtherKey="dh_ma")]
		public EntitySet<dathang> dathangs
		{
			get
			{
				return this._dathangs;
			}
			set
			{
				this._dathangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_chitietdathang", Storage="_khachhang", ThisKey="ctdh_makh", OtherKey="kh_ma", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.chitietdathangs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.chitietdathangs.Add(this);
						this._ctdh_makh = value.kh_ma;
					}
					else
					{
						this._ctdh_makh = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dathangs(dathang entity)
		{
			this.SendPropertyChanging();
			entity.chitietdathang = this;
		}
		
		private void detach_dathangs(dathang entity)
		{
			this.SendPropertyChanging();
			entity.chitietdathang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dathang")]
	public partial class dathang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dh_ma;
		
		private System.Nullable<int> _dh_soluong;
		
		private int _dh_madt;
		
		private EntityRef<chitietdathang> _chitietdathang;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondh_maChanging(int value);
    partial void Ondh_maChanged();
    partial void Ondh_soluongChanging(System.Nullable<int> value);
    partial void Ondh_soluongChanged();
    partial void Ondh_madtChanging(int value);
    partial void Ondh_madtChanged();
    #endregion
		
		public dathang()
		{
			this._chitietdathang = default(EntityRef<chitietdathang>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dh_ma", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dh_ma
		{
			get
			{
				return this._dh_ma;
			}
			set
			{
				if ((this._dh_ma != value))
				{
					if (this._chitietdathang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondh_maChanging(value);
					this.SendPropertyChanging();
					this._dh_ma = value;
					this.SendPropertyChanged("dh_ma");
					this.Ondh_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dh_soluong", DbType="Int")]
		public System.Nullable<int> dh_soluong
		{
			get
			{
				return this._dh_soluong;
			}
			set
			{
				if ((this._dh_soluong != value))
				{
					this.Ondh_soluongChanging(value);
					this.SendPropertyChanging();
					this._dh_soluong = value;
					this.SendPropertyChanged("dh_soluong");
					this.Ondh_soluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dh_madt", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dh_madt
		{
			get
			{
				return this._dh_madt;
			}
			set
			{
				if ((this._dh_madt != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondh_madtChanging(value);
					this.SendPropertyChanging();
					this._dh_madt = value;
					this.SendPropertyChanged("dh_madt");
					this.Ondh_madtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chitietdathang_dathang", Storage="_chitietdathang", ThisKey="dh_ma", OtherKey="ctdh_madh", IsForeignKey=true)]
		public chitietdathang chitietdathang
		{
			get
			{
				return this._chitietdathang.Entity;
			}
			set
			{
				chitietdathang previousValue = this._chitietdathang.Entity;
				if (((previousValue != value) 
							|| (this._chitietdathang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chitietdathang.Entity = null;
						previousValue.dathangs.Remove(this);
					}
					this._chitietdathang.Entity = value;
					if ((value != null))
					{
						value.dathangs.Add(this);
						this._dh_ma = value.ctdh_madh;
					}
					else
					{
						this._dh_ma = default(int);
					}
					this.SendPropertyChanged("chitietdathang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_dathang", Storage="_sanpham", ThisKey="dh_madt", OtherKey="sp_ma", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.dathangs.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.dathangs.Add(this);
						this._dh_madt = value.sp_ma;
					}
					else
					{
						this._dh_madt = default(int);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhasanxuat")]
	public partial class nhasanxuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nsx_ma;
		
		private string _nsx_ten;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnsx_maChanging(int value);
    partial void Onnsx_maChanged();
    partial void Onnsx_tenChanging(string value);
    partial void Onnsx_tenChanged();
    #endregion
		
		public nhasanxuat()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsx_ma", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nsx_ma
		{
			get
			{
				return this._nsx_ma;
			}
			set
			{
				if ((this._nsx_ma != value))
				{
					this.Onnsx_maChanging(value);
					this.SendPropertyChanging();
					this._nsx_ma = value;
					this.SendPropertyChanged("nsx_ma");
					this.Onnsx_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsx_ten", DbType="NVarChar(30)")]
		public string nsx_ten
		{
			get
			{
				return this._nsx_ten;
			}
			set
			{
				if ((this._nsx_ten != value))
				{
					this.Onnsx_tenChanging(value);
					this.SendPropertyChanging();
					this._nsx_ten = value;
					this.SendPropertyChanged("nsx_ten");
					this.Onnsx_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhasanxuat_sanpham", Storage="_sanphams", ThisKey="nsx_ma", OtherKey="sp_nsx")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.nhasanxuat = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.nhasanxuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kh_ma;
		
		private string _kh_ten;
		
		private string _kh_diachi;
		
		private System.Nullable<int> _kh_sdt;
		
		private string _kh_matkhau;
		
		private EntitySet<chitietdathang> _chitietdathangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkh_maChanging(int value);
    partial void Onkh_maChanged();
    partial void Onkh_tenChanging(string value);
    partial void Onkh_tenChanged();
    partial void Onkh_diachiChanging(string value);
    partial void Onkh_diachiChanged();
    partial void Onkh_sdtChanging(System.Nullable<int> value);
    partial void Onkh_sdtChanged();
    partial void Onkh_matkhauChanging(string value);
    partial void Onkh_matkhauChanged();
    #endregion
		
		public khachhang()
		{
			this._chitietdathangs = new EntitySet<chitietdathang>(new Action<chitietdathang>(this.attach_chitietdathangs), new Action<chitietdathang>(this.detach_chitietdathangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_ma", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int kh_ma
		{
			get
			{
				return this._kh_ma;
			}
			set
			{
				if ((this._kh_ma != value))
				{
					this.Onkh_maChanging(value);
					this.SendPropertyChanging();
					this._kh_ma = value;
					this.SendPropertyChanged("kh_ma");
					this.Onkh_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_ten", DbType="NVarChar(30)")]
		public string kh_ten
		{
			get
			{
				return this._kh_ten;
			}
			set
			{
				if ((this._kh_ten != value))
				{
					this.Onkh_tenChanging(value);
					this.SendPropertyChanging();
					this._kh_ten = value;
					this.SendPropertyChanged("kh_ten");
					this.Onkh_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_diachi", DbType="NVarChar(100)")]
		public string kh_diachi
		{
			get
			{
				return this._kh_diachi;
			}
			set
			{
				if ((this._kh_diachi != value))
				{
					this.Onkh_diachiChanging(value);
					this.SendPropertyChanging();
					this._kh_diachi = value;
					this.SendPropertyChanged("kh_diachi");
					this.Onkh_diachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_sdt", DbType="Int")]
		public System.Nullable<int> kh_sdt
		{
			get
			{
				return this._kh_sdt;
			}
			set
			{
				if ((this._kh_sdt != value))
				{
					this.Onkh_sdtChanging(value);
					this.SendPropertyChanging();
					this._kh_sdt = value;
					this.SendPropertyChanged("kh_sdt");
					this.Onkh_sdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_matkhau", DbType="NVarChar(50)")]
		public string kh_matkhau
		{
			get
			{
				return this._kh_matkhau;
			}
			set
			{
				if ((this._kh_matkhau != value))
				{
					this.Onkh_matkhauChanging(value);
					this.SendPropertyChanging();
					this._kh_matkhau = value;
					this.SendPropertyChanged("kh_matkhau");
					this.Onkh_matkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_chitietdathang", Storage="_chitietdathangs", ThisKey="kh_ma", OtherKey="ctdh_makh")]
		public EntitySet<chitietdathang> chitietdathangs
		{
			get
			{
				return this._chitietdathangs;
			}
			set
			{
				this._chitietdathangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdathangs(chitietdathang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_chitietdathangs(chitietdathang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sp_ma;
		
		private string _sp_ten;
		
		private System.Nullable<int> _sp_nsx;
		
		private string _sp_mota;
		
		private string _sp_giatien;
		
		private string _sp_manhinh;
		
		private string _sp_hdh;
		
		private string _sp_camera;
		
		private string _sp_cpu;
		
		private string _sp_ram;
		
		private string _sp_rom;
		
		private string _sp_pin;
		
		private EntitySet<dathang> _dathangs;
		
		private EntityRef<nhasanxuat> _nhasanxuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsp_maChanging(int value);
    partial void Onsp_maChanged();
    partial void Onsp_tenChanging(string value);
    partial void Onsp_tenChanged();
    partial void Onsp_nsxChanging(System.Nullable<int> value);
    partial void Onsp_nsxChanged();
    partial void Onsp_motaChanging(string value);
    partial void Onsp_motaChanged();
    partial void Onsp_giatienChanging(string value);
    partial void Onsp_giatienChanged();
    partial void Onsp_manhinhChanging(string value);
    partial void Onsp_manhinhChanged();
    partial void Onsp_hdhChanging(string value);
    partial void Onsp_hdhChanged();
    partial void Onsp_cameraChanging(string value);
    partial void Onsp_cameraChanged();
    partial void Onsp_cpuChanging(string value);
    partial void Onsp_cpuChanged();
    partial void Onsp_ramChanging(string value);
    partial void Onsp_ramChanged();
    partial void Onsp_romChanging(string value);
    partial void Onsp_romChanged();
    partial void Onsp_pinChanging(string value);
    partial void Onsp_pinChanged();
    #endregion
		
		public sanpham()
		{
			this._dathangs = new EntitySet<dathang>(new Action<dathang>(this.attach_dathangs), new Action<dathang>(this.detach_dathangs));
			this._nhasanxuat = default(EntityRef<nhasanxuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_ma", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sp_ma
		{
			get
			{
				return this._sp_ma;
			}
			set
			{
				if ((this._sp_ma != value))
				{
					this.Onsp_maChanging(value);
					this.SendPropertyChanging();
					this._sp_ma = value;
					this.SendPropertyChanged("sp_ma");
					this.Onsp_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_ten", DbType="NVarChar(50)")]
		public string sp_ten
		{
			get
			{
				return this._sp_ten;
			}
			set
			{
				if ((this._sp_ten != value))
				{
					this.Onsp_tenChanging(value);
					this.SendPropertyChanging();
					this._sp_ten = value;
					this.SendPropertyChanged("sp_ten");
					this.Onsp_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_nsx", DbType="Int")]
		public System.Nullable<int> sp_nsx
		{
			get
			{
				return this._sp_nsx;
			}
			set
			{
				if ((this._sp_nsx != value))
				{
					if (this._nhasanxuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsp_nsxChanging(value);
					this.SendPropertyChanging();
					this._sp_nsx = value;
					this.SendPropertyChanged("sp_nsx");
					this.Onsp_nsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_mota", DbType="NVarChar(30)")]
		public string sp_mota
		{
			get
			{
				return this._sp_mota;
			}
			set
			{
				if ((this._sp_mota != value))
				{
					this.Onsp_motaChanging(value);
					this.SendPropertyChanging();
					this._sp_mota = value;
					this.SendPropertyChanged("sp_mota");
					this.Onsp_motaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_giatien", DbType="NVarChar(30)")]
		public string sp_giatien
		{
			get
			{
				return this._sp_giatien;
			}
			set
			{
				if ((this._sp_giatien != value))
				{
					this.Onsp_giatienChanging(value);
					this.SendPropertyChanging();
					this._sp_giatien = value;
					this.SendPropertyChanged("sp_giatien");
					this.Onsp_giatienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_manhinh", DbType="NVarChar(100)")]
		public string sp_manhinh
		{
			get
			{
				return this._sp_manhinh;
			}
			set
			{
				if ((this._sp_manhinh != value))
				{
					this.Onsp_manhinhChanging(value);
					this.SendPropertyChanging();
					this._sp_manhinh = value;
					this.SendPropertyChanged("sp_manhinh");
					this.Onsp_manhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_hdh", DbType="NVarChar(50)")]
		public string sp_hdh
		{
			get
			{
				return this._sp_hdh;
			}
			set
			{
				if ((this._sp_hdh != value))
				{
					this.Onsp_hdhChanging(value);
					this.SendPropertyChanging();
					this._sp_hdh = value;
					this.SendPropertyChanged("sp_hdh");
					this.Onsp_hdhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_camera", DbType="NVarChar(50)")]
		public string sp_camera
		{
			get
			{
				return this._sp_camera;
			}
			set
			{
				if ((this._sp_camera != value))
				{
					this.Onsp_cameraChanging(value);
					this.SendPropertyChanging();
					this._sp_camera = value;
					this.SendPropertyChanged("sp_camera");
					this.Onsp_cameraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_cpu", DbType="NVarChar(50)")]
		public string sp_cpu
		{
			get
			{
				return this._sp_cpu;
			}
			set
			{
				if ((this._sp_cpu != value))
				{
					this.Onsp_cpuChanging(value);
					this.SendPropertyChanging();
					this._sp_cpu = value;
					this.SendPropertyChanged("sp_cpu");
					this.Onsp_cpuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_ram", DbType="NVarChar(30)")]
		public string sp_ram
		{
			get
			{
				return this._sp_ram;
			}
			set
			{
				if ((this._sp_ram != value))
				{
					this.Onsp_ramChanging(value);
					this.SendPropertyChanging();
					this._sp_ram = value;
					this.SendPropertyChanged("sp_ram");
					this.Onsp_ramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_rom", DbType="NVarChar(30)")]
		public string sp_rom
		{
			get
			{
				return this._sp_rom;
			}
			set
			{
				if ((this._sp_rom != value))
				{
					this.Onsp_romChanging(value);
					this.SendPropertyChanging();
					this._sp_rom = value;
					this.SendPropertyChanged("sp_rom");
					this.Onsp_romChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_pin", DbType="NVarChar(50)")]
		public string sp_pin
		{
			get
			{
				return this._sp_pin;
			}
			set
			{
				if ((this._sp_pin != value))
				{
					this.Onsp_pinChanging(value);
					this.SendPropertyChanging();
					this._sp_pin = value;
					this.SendPropertyChanged("sp_pin");
					this.Onsp_pinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_dathang", Storage="_dathangs", ThisKey="sp_ma", OtherKey="dh_madt")]
		public EntitySet<dathang> dathangs
		{
			get
			{
				return this._dathangs;
			}
			set
			{
				this._dathangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhasanxuat_sanpham", Storage="_nhasanxuat", ThisKey="sp_nsx", OtherKey="nsx_ma", IsForeignKey=true)]
		public nhasanxuat nhasanxuat
		{
			get
			{
				return this._nhasanxuat.Entity;
			}
			set
			{
				nhasanxuat previousValue = this._nhasanxuat.Entity;
				if (((previousValue != value) 
							|| (this._nhasanxuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhasanxuat.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._nhasanxuat.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._sp_nsx = value.nsx_ma;
					}
					else
					{
						this._sp_nsx = default(Nullable<int>);
					}
					this.SendPropertyChanged("nhasanxuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dathangs(dathang entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_dathangs(dathang entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tintuc")]
	public partial class tintuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tt_ma;
		
		private string _tt_tieude;
		
		private string _tt_mota;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontt_maChanging(int value);
    partial void Ontt_maChanged();
    partial void Ontt_tieudeChanging(string value);
    partial void Ontt_tieudeChanged();
    partial void Ontt_motaChanging(string value);
    partial void Ontt_motaChanged();
    #endregion
		
		public tintuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_ma", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int tt_ma
		{
			get
			{
				return this._tt_ma;
			}
			set
			{
				if ((this._tt_ma != value))
				{
					this.Ontt_maChanging(value);
					this.SendPropertyChanging();
					this._tt_ma = value;
					this.SendPropertyChanged("tt_ma");
					this.Ontt_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_tieude", DbType="NVarChar(50)")]
		public string tt_tieude
		{
			get
			{
				return this._tt_tieude;
			}
			set
			{
				if ((this._tt_tieude != value))
				{
					this.Ontt_tieudeChanging(value);
					this.SendPropertyChanging();
					this._tt_tieude = value;
					this.SendPropertyChanged("tt_tieude");
					this.Ontt_tieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_mota", DbType="NVarChar(1000)")]
		public string tt_mota
		{
			get
			{
				return this._tt_mota;
			}
			set
			{
				if ((this._tt_mota != value))
				{
					this.Ontt_motaChanging(value);
					this.SendPropertyChanging();
					this._tt_mota = value;
					this.SendPropertyChanged("tt_mota");
					this.Ontt_motaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
