<?xml version="1.0" encoding="utf-8"?><Database Name="DA_WebBanDienThoai" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-S60J4U2U\SQLEXPRESSS;Initial Catalog=DA_WebBanDienThoai;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DA_WebBanDienThoaiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.chitietdathang" Member="chitietdathangs">
    <Type Name="chitietdathang">
      <Column Name="ctdh_madh" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ctdh_makh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ctdh_ngaylap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ctdh_tongtien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="chitietdathang_dathang" Member="dathangs" ThisKey="ctdh_madh" OtherKey="dh_ma" Type="dathang" />
      <Association Name="khachhang_chitietdathang" Member="khachhang" ThisKey="ctdh_makh" OtherKey="kh_ma" Type="khachhang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dathang" Member="dathangs">
    <Type Name="dathang">
      <Column Name="dh_ma" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dh_soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dh_madt" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="chitietdathang_dathang" Member="chitietdathang" ThisKey="dh_ma" OtherKey="ctdh_madh" Type="chitietdathang" IsForeignKey="true" />
      <Association Name="sanpham_dathang" Member="sanpham" ThisKey="dh_madt" OtherKey="sp_ma" Type="sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.nhasanxuat" Member="nhasanxuats">
    <Type Name="nhasanxuat">
      <Column Name="nsx_ma" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nsx_ten" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="nhasanxuat_sanpham" Member="sanphams" ThisKey="nsx_ma" OtherKey="sp_nsx" Type="sanpham" />
    </Type>
  </Table>
  <Table Name="dbo.khachhang" Member="khachhangs">
    <Type Name="khachhang">
      <Column Name="kh_ma" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="kh_ten" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="kh_diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="kh_sdt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kh_matkhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="khachhang_chitietdathang" Member="chitietdathangs" ThisKey="kh_ma" OtherKey="ctdh_makh" Type="chitietdathang" />
    </Type>
  </Table>
  <Table Name="dbo.sanpham" Member="sanphams">
    <Type Name="sanpham">
      <Column Name="sp_ma" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sp_ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sp_nsx" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sp_mota" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="sp_giatien" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="sp_manhinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sp_hdh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sp_camera" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sp_cpu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sp_ram" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="sp_rom" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="sp_pin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="sanpham_dathang" Member="dathangs" ThisKey="sp_ma" OtherKey="dh_madt" Type="dathang" />
      <Association Name="nhasanxuat_sanpham" Member="nhasanxuat" ThisKey="sp_nsx" OtherKey="nsx_ma" Type="nhasanxuat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tintuc" Member="tintucs">
    <Type Name="tintuc">
      <Column Name="tt_ma" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tt_tieude" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tt_mota" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>